### ISSUE TITLE
Trailing parenthesis in os string

### ISSUE THREAD

**Issue by Rudloff** [hankchizljaw/mybrowser.fyi-project#19]
## Link to mybrowser.fyi report

https://mybrowser.fyi/report/5b526bf2d9804d0014f1d539/json

## Brief description of what went wrong
There is a trailing parenthesis in `os`.

## Steps to reproduce the issue
Browse to https://mybrowser.fyi/ with an app using the Android 7.1.2 webview.

## Any other notes

The user-agent is `Mozilla/5.0 (Linux; Android 7.1.2) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.2 Chrome/52.0.2743.100 Mobile Safari/537.36 `.

**Comment by hankchizljaw** [comment]
Thanks for reporting this 🙂

**Comment by Andy-set-studio** [comment]
Fixed in `v0.1.1`: https://github.com/hankchizljaw/mybrowser.fyi-project/releases/tag/v0.1.1
