### ISSUE TITLE
Doesn't recognize either Otter nor Vivaldi

### ISSUE THREAD

**Issue by Cqoicebordel** [hankchizljaw/mybrowser.fyi-project#22]
## Report URL
https://mybrowser.fyi/report/5b5611817e8a1100147ef5e8

Doesn't detect correctly either Otter Browser (https://otter-browser.org/) nor Vivaldi (https://vivaldi.com/)

## To reproduce
Install those browsers and test them.

**Comment by Andy-set-studio** [comment]
Fixed in `v0.1.1`: https://github.com/hankchizljaw/mybrowser.fyi-project/releases/tag/v0.1.1
