### ISSUE TITLE
Firefox is showing JSON response instead of visualize data

### ISSUE THREAD

**Issue by swarnava** [hankchizljaw/mybrowser.fyi-project#26]
## Brief description of what went wrong
**Expected Behavior**:-
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/1162991/43354863-154b412a-9271-11e8-9ff1-d6781a82197b.png">

**Current Behavior on Firefox**:-
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/1162991/43354851-eecc52fa-9270-11e8-9fe8-bd022d2365a0.png">

**Comment by Andy-set-studio** [comment]
Hey there, this is in fact progressive enhancement in action, because Firefox doesn’t support custom elements yet.

**Comment by swarnava** [comment]
You are right, setting **dom.webcomponents.customelements.enabled** to **true** worked!
