### ISSUE TITLE
https://mybrowser.fyi Cloudflare connection timed out error?

### ISSUE THREAD

**Issue by Ambient-Impact** [hankchizljaw/mybrowser.fyi-project#33]
## Link to mybrowser.fyi report
N/A

## Brief description of what went wrong
I'm getting [this Cloudflare error](https://screenshots.firefox.com/35jJAj2eABCwaKWc/mybrowser.fyi) the last couple of days when trying to load the site. :(

## Steps to reproduce the issue
Attempt to visit https://mybrowser.fyi

**Comment by Andy-set-studio** [comment]
Hey @Ambient-Impact, thanks for alerting me to this. I'm not quite sure what's happening, but I'm thinking it could be a Cloudflare issue as the app is working fine: https://mybrowser-fyi.herokuapp.com

I'll have a poke around.

Thanks again!

**Comment by Andy-set-studio** [comment]
Fixed it! It was a Cloudflare and DNS issue. Again, thanks so much for alerting me to that. It's super appreciated :)

**Comment by Ambient-Impact** [comment]
Glad I could help. I've been bitten before by DNS stuff and Cloudflare.

**Comment by Ambient-Impact** [comment]
Now that I've had a chance to give it a try, I've added [a link on my site to it](https://ambientimpact.com/web/snippets/my-browser-easy-to-digest-browser-details-to-help-you-with-qa-and-tech-support). 😄

**Comment by Andy-set-studio** [comment]
Oh nice one! Thanks very much 🙂
