### ISSUE TITLE
Link to Seanau on iconfinder returns a 404

### ISSUE THREAD

**Issue by NicholasMurray** [hankchizljaw/mybrowser.fyi-project#37]
## Link to mybrowser.fyi report
https://mybrowser.fyi/report/5cd1a44b4a81d200152f1fa2
https://www.iconfinder.com/seanauicons

## Brief description of what went wrong
Clicked on link to Seanau on iconfinder and received 404

## Steps to reproduce the issue
Click on link to Seanau at bottom of page

**Comment by Andy-set-studio** [comment]
Cheers @NicholasMurray! I only added this item to give them a little boost, so if their store isn't there any more, there's no point in the link being there.

I've pushed up a change that gets rid of that: https://mybrowser.fyi/report/5cd405f60a694400155c0c2f

**Comment by taylortrimble** [comment]
FYI, if you'd still like to boost your icons' designer, Seanau has a website: https://www.seanau.com.

I believe the icons you used are in the "Charm" icon set.

**Comment by Andy-set-studio** [comment]
Nice one!
